source 'https://rubygems.org'

gem 'jekyll'
gem 'webrick'
gem 'jekyll-watch'
gem 'kramdown-parser-gfm'

group :jekyll_plugins do
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
    gem 'jekyll-sitemap'
end